// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSLCricketAPI.DataAccess;

namespace NSLCricketAPI.DataAccess.Migrations
{
    [DbContext(typeof(NSLDbContext))]
    [Migration("20211221070201_InitialWithPlayerData")]
    partial class InitialWithPlayerData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NSLCricketAPI.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("joinedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            fName = "Sudeera",
                            joinedOn = new DateTime(2021, 12, 1, 18, 2, 0, 345, DateTimeKind.Local).AddTicks(4438),
                            lName = "Ilandarage",
                            role = 2
                        },
                        new
                        {
                            ID = 2,
                            fName = "Thilina",
                            joinedOn = new DateTime(2021, 12, 11, 18, 2, 0, 355, DateTimeKind.Local).AddTicks(1062),
                            lName = "Kalu Malli",
                            role = 3
                        },
                        new
                        {
                            ID = 3,
                            fName = "Punya",
                            joinedOn = new DateTime(2021, 12, 11, 18, 2, 0, 355, DateTimeKind.Local).AddTicks(1252),
                            lName = "Abaya",
                            role = 5
                        },
                        new
                        {
                            ID = 4,
                            fName = "Shehan",
                            joinedOn = new DateTime(2021, 12, 6, 18, 2, 0, 355, DateTimeKind.Local).AddTicks(1271),
                            lName = "De Silva",
                            role = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
