// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSLCricketAPI.DataAccess;

namespace NSLCricketAPI.DataAccess.Migrations
{
    [DbContext(typeof(NSLDbContext))]
    [Migration("20211221225555_Performances")]
    partial class Performances
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NSLCricketAPI.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GameDay")
                        .HasColumnType("datetime2");

                    b.Property<float>("Overs")
                        .HasColumnType("real");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Runs")
                        .HasColumnType("int");

                    b.Property<int>("Wickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Performances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameDay = new DateTime(2021, 12, 18, 9, 55, 54, 512, DateTimeKind.Local).AddTicks(974),
                            Overs = 0f,
                            PlayerId = 1,
                            Runs = 28,
                            Wickets = 0
                        },
                        new
                        {
                            Id = 2,
                            GameDay = new DateTime(2021, 12, 18, 9, 55, 54, 512, DateTimeKind.Local).AddTicks(4112),
                            Overs = 6f,
                            PlayerId = 4,
                            Runs = 56,
                            Wickets = 2
                        },
                        new
                        {
                            Id = 3,
                            GameDay = new DateTime(2021, 12, 18, 9, 55, 54, 512, DateTimeKind.Local).AddTicks(4147),
                            Overs = 3f,
                            PlayerId = 3,
                            Runs = 9,
                            Wickets = 1
                        });
                });

            modelBuilder.Entity("NSLCricketAPI.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("joinedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("lName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            fName = "Sudeera",
                            joinedOn = new DateTime(2021, 12, 2, 9, 55, 54, 501, DateTimeKind.Local).AddTicks(7137),
                            lName = "Ilandarage",
                            role = 2
                        },
                        new
                        {
                            ID = 2,
                            fName = "Thilina",
                            joinedOn = new DateTime(2021, 12, 12, 9, 55, 54, 509, DateTimeKind.Local).AddTicks(7201),
                            lName = "Kalu Malli",
                            role = 3
                        },
                        new
                        {
                            ID = 3,
                            fName = "Punya",
                            joinedOn = new DateTime(2021, 12, 12, 9, 55, 54, 509, DateTimeKind.Local).AddTicks(7278),
                            lName = "Abaya",
                            role = 5
                        },
                        new
                        {
                            ID = 4,
                            fName = "Shehan",
                            joinedOn = new DateTime(2021, 12, 7, 9, 55, 54, 509, DateTimeKind.Local).AddTicks(7288),
                            lName = "De Silva",
                            role = 4
                        });
                });

            modelBuilder.Entity("NSLCricketAPI.Models.Performance", b =>
                {
                    b.HasOne("NSLCricketAPI.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
